WEEWX_ROOT = /tmp/simrun
debug = 0
version = 5.5.0
socket_timeout = 20

[Station]
    location = Test
    latitude = 48.0
    longitude = 11.5
    altitude = 500, meter
    station_type = Simulator
    rain_year_start = 1
    week_start = 6

[Simulator]
    driver = weewx.drivers.simulator
    loop_interval = 2.5
    mode = generator
    start = 2026-08-25T00:00

[StdConvert]
    target_unit = US

[StdArchive]
    archive_interval = 300
    archive_delay = 15
    record_generation = software
    loop_hilo = True
    data_binding = wx_binding
    retain_days = 7
    archive_days = 365
    ingest_binding = loop_binding

[DataBindings]
    [[wx_binding]]
        database = archive_sqlite
        table_name = archive
        manager = weewx.manager.DaySummaryManager
        schema = weewx.schemas.wview_extended.schema
    [[loop_binding]]
        database = loop_sqlite
        table_name = packets
        manager = weewx.loopstore.LoopStore
        schema = weewx.loopstore.schema

[Databases]
    [[archive_sqlite]]
        database_name = sim.sdb
        database_type = SQLite
    [[loop_sqlite]]
        database_name = sim-loop.sdb
        database_type = SQLite

[DatabaseTypes]
    [[SQLite]]
        driver = weedb.sqlite
        SQLITE_ROOT = /tmp/simrun/archive

[Engine]
    [[Services]]
        prep_services = weewx.engine.StdTimeSynch
        data_services = ,
        process_services = weewx.engine.StdConvert, weewx.engine.StdCalibrate, weewx.engine.StdQC, weewx.wxservices.StdWXCalculate
        xtype_services = weewx.wxxtypes.StdWXXTypes, weewx.wxxtypes.StdPressureCooker, weewx.wxxtypes.StdRainRater, weewx.wxxtypes.StdDelta
        archive_services = weewx.engine.StdArchive
        restful_services = ,
        report_services = ,

[Logging]
    [[root]]
      handlers = console,
      level = INFO
    [[handlers]]
      [[[console]]]
        level = INFO
        formatter = standard
        class = logging.StreamHandler
        stream = ext://sys.stdout
